// libraries import
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <math.h>
#include <sstream>
#include <map>
#include <limits>

// constant definition
#define maxBitLength	300
#define stringLimit	1000
#define eventsLimit	1000
#define scenariosLimit	700
#define predicatesLimit	200

#define WELCOME_STRING "# Log file generated by SCENCO v0.1\n\n"

using namespace std;
