// libraries import
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <math.h>
#include <sstream>
#include <map>
#include <limits>

// constant definition
#define MAX_NAME	300	  // Max length name for each node
#define EXHAUSTIVE_MAX_PERM 1000  // Max number of permutation

#define stringLimit	1000
#define eventsLimit	1000
#define scenariosLimit	700
#define predicatesLimit	200

#define WELCOME_STRING "# Log file generated by SCENCO v.0.1 / encoding\n\n"

using namespace std;
